### ISSUE TITLE
AppendTargetFrameworkToOutputPath not respected by PackageFile target

### ISSUE THREAD

**Issue by jzabroski** [devlooped/nugetizer#105]
## Describe the Bug

AppendTargetFrameworkToOutputPath not respected by PackageFile target, such that the output from `dotnet nugetize custom.csproj` is as follows:

```
Package: Custom.0.0.0.1-dev.nupkg
         D:\Users\John.Zabroski\source\infrastructure\trunk\Prototype\bin\Custom.nuspec
    Authors    : John.Zabroski
    Copyright  : Simmaculate c 2021
    Description: Package Description
    Icon       : icon.png
    Version    : 0.0.0.1-dev
  Contents:
    /contentFiles/
      any/
        net5.0/
          ThirdParty.OData

```

## Steps to Reproduce

I don't know how to provide a unit test for MSBuild related stuff.

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <!-- ReSharper disable UnknownProperty -->  
  <PropertyGroup>
    <Authors>John Zabroski</Authors>
    <Copyright>Simmaculate</Copyright>
    <TargetFramework>net5.0</TargetFramework> <!--netcoreapp2.1, netcoreapp3.1 also supported -->
    <EnablePackInference>false</EnablePackInference>
    <PackageIcon>icon.png</PackageIcon>
    <PackageId>Custom</PackageId>
    <AssemblyTitle>Custom Packaging</AssemblyTitle>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>bin</OutputPath>
  </PropertyGroup>

  <PropertyGroup>
    <PackDependencies>true</PackDependencies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Nugetizer" Version="*" />
    <PackageReference Include="ThirdParty.OData" Version="*" >
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <PackageFile Include="ThirdParty.OData" Version="*" PackFolder="Content" Pack="true" />
  </ItemGroup>

</Project>
```

## Expected Behavior

Based on AppendTargetFrameworkToOutputPath=false and PackDependencies=true and OutputPath=bin, I would expect the third party nuget package to be transcluded into the bin folder, and the /any/net5.0 sub-tree to be deforested so that its just "/contentFiles/<all ThirdParty.Odata dependencies>".

## Exception with Stack Trace

n/a

## Version Info

dotnet-nugetize 0.7, Nugetizer 0.7

## Additional Info

I figured I would use this prototype as research into @kzu suggesting I give Nugetizer a try to solve problems with SDK Pack, but so far I am not fully wrapping my head around how this is supposed to work, and I am most definitely not an MSBuild or Nuget expert.

**Comment by jzabroski** [comment]
Changing
```xml
  <ItemGroup>
    <PackageFile Include="ThirdParty.OData" Version="*" PackFolder="Content" Pack="true" />
  </ItemGroup>
```
to:
```xml
  <ItemGroup>
    <PackageFile Include="ThirdParty.OData" Version="*" PackFolder="Content" Pack="true" FrameworkSpecific="false" />
  </ItemGroup>
```

Generates the following instead:

```
Package: Custom.0.0.0.1-dev.nupkg
         D:\Users\John.Zabroski\source\infrastructure\trunk\Prototype\bin\Custom.nuspec
    Authors    : John.Zabroski
    Copyright  : Simmaculate c 2021
    Description: Package Description
    Icon       : icon.png
    Version    : 0.0.0.1-dev
  Contents:
    /contentFiles/
      any/
        any/
          ThirdParty.OData
```

Not exactly what I was expecting.

**Comment by jzabroski** [comment]
I did find PackagePath but I am not sure I understand how to properly use it.  Can you point me to the nuget docs that have the specific rules for Content/ContentFiles?  In the SDK Pack world, all I have to know about is whether an item is Content or not, so I am not familiar with specific rules, as I am guessing SDK Pack hides them from me?

I think my confusion comes from trying to follow this example on your blog post:

```xml
    <!-- Add package dependencies directly too -->
    <PackageFile Include="Newtonsoft.Json" Version="13.0.1" PackFolder="Dependency" />
```
I didn't realize that what you were implying is I could avoid nuget restore entirely by simply forcing the dependency information.  I thought PackageFile Include="Newtonsoft.Json" might somehow automagically download the package and provide us with the option to include all packagereferences in a single package, similar to what Cake and OctoPack do.

**Comment by kzu** [comment]
https://devblogs.microsoft.com/nuget/nuget-contentfiles-demystified/
https://docs.microsoft.com/en-us/nuget/reference/nuspec#including-content-files

**Comment by jzabroski** [comment]
It also looks like ContentTargetFolders isn't respected.  Not sure if it should be.  Mostly just going off the description that Nugetizer is mostly a drop-in replacement for "SDK Pack".  Seems like a reasonable expectation it should, based on https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#including-content-in-a-package

**Comment by kzu** [comment]
Plz provide the csproj with the content laid out by SDK Pack and how nugetizer differs from that. (after just referencing nugetizer, no csproj changes, aka "drop in replacement" :))

Thanks!

**Comment by kzu** [comment]
Also, perhaps change the issue title since `AppendTargetFrameworkToOutputPath` doesn't play a role in SDK pack or nugetizer alike?
