### ISSUE TITLE
dotnet.exe nugetize My.sln errors if one project doesn't PackageReference Nugetizer

### ISSUE THREAD

**Issue by jzabroski** [devlooped/nugetizer#107]
## Describe the Bug

dotnet.exe nugetize My.sln errors if one project doesn't PackageReference Nugetizer

## Steps to Reproduce

Create a solution with two projects, /A/A.csproj and /B/B.csproj and only A.csproj references Nugetizer:

```xml
<PackageReference Include="Nugetizer" Version="*" />
```

run `dotnet.exe nugetize` on the top-level folder containing the solution file.

## Expected Behavior

Plain Old CSProj should not need to know about nugetizer.

Alternatively, or additionally, there should be a nugetize option to warn or silence warnings related to projects not having a PackageReference to Nugetizer.

Alternatively, it seems like there is some additional error checking that should happen on the csproj itself, such that it could check that PackageReference Include="Nugetizer" is present or not.  However, that could have versioning issues depending on how dotnet-nugetize is built due to assembly version mismatches between Nugetizer and dotnet-nugetize.

## Exception with Stack Trace

```text
PS D:\Users\John.Zabroski\source\infrastructure2\master\Prototype> dotnet.exe nugetize
D:\Users\John.Zabroski\source\infrastructure2\master\Prototype\B.csproj : error MSB4057: The target "GetPackageContents" does not exist in the project.
```

## Version Info

0.7

## Additional Info

n/a

**Comment by kzu** [comment]
Good point. In fact, there is a way to test whether a project has been nugetized :). Will use that to detect and show a more meaningful warning.

**Comment by kzu** [comment]
Thanks for your suggestion @jzabroski! I just fixed and pushed the fix to nuget.org, v0.7.4 has it.

**Comment by jzabroski** [comment]
@kzu Thank you. 🧸
