### ISSUE TITLE
No longer able to generate separate snupkg symbol packages.

### ISSUE THREAD

**Issue by mhsimkin** [devlooped/nugetizer#117]
[msbuild-nugetize.log](https://github.com/devlooped/nugetizer/files/6704503/msbuild-nugetize.log)
[msbuild.log](https://github.com/devlooped/nugetizer/files/6704504/msbuild.log)
Once you add nugetize as a package to your projects, it is no longer possible to generate a separate symbol packages as per the discussion here: [https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg ).

I am relying on setting the `<IncludeSymbols>` and `<SymbolPackageFormat>` to generate the separate files that are then pushed to a package server and a symbol server respectively.

I have a global target file that is included in all my projects that has the settings for `<IncludeSymbols>` and `<SymbolPackageFormat>` and other properties that control the source link and repository url.

This is my target file:
```
<Project>
  <PropertyGroup>
    <!-- Optional: Publish the repository URL in the built .nupkg (in the NuSpec <Repository> element) -->
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
 
    <!-- Optional: Embed source files that are not tracked by the source control manager in the PDB -->
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
  
    <!-- Optional: Build symbol package (.snupkg) to distribute the PDB containing Source Link -->
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.Bitbucket.Git" Version="1.0.0-beta2-19367-01" PrivateAssets="All"/>
    <SourceLinkBitbucketGitHost Include="source.host.com" Version="3.7.1"/>
  </ItemGroup>
</Project>
```
Then as the last item in my .csproj file I import the symbol target file:
```
Import Project="$(SolutionDir)..\SymbolConfiguration.targets" />
```
I have provided MSBuild logs.  The msbuild.log file works as expected and generates the separate symbol package.  The msbuild-nugetize.log creates one package that contains the dlls and the symbols.

Is there a way to have a separate symbol package generated?

Thanks

-marc

**Comment by kzu** [comment]
Nugetizer does not do separate symbol packages. Use SDK pack for that. 

I consider separate symbol packages a legacy feature from a time when PDBs were not portable, were huge and nuget didn't have a central cache in your machine (therefore taking huge amount of space for each and every solution). None of that is the case today, so this is highly unlikely to ever happen in this project.

**Comment by kzu** [comment]
FWIW, nugetizer is a *replacement* to SDK pack.

**Comment by loic-sharma** [comment]
FYI, nuget.org does not ingest portable PDBs contained in the .nupkg. If you want to use nuget.org's symbol server, you will need to create a separate .snupkg file.

**Comment by kzu** [comment]
Why would I ever want to use nuget.org's symbol server? Symbol servers are the past 😉 .

Just put the pdb in the package or even better, embed it in the library. See https://twitter.com/kzu/status/953694190826909696
