### ISSUE TITLE
Cannot place .NET Framework 4.7.2 project reference dll inside lib\net5.0\SpecificFolder

### ISSUE THREAD

**Issue by denjmpr** [devlooped/nugetizer#118]
## Describe the Bug

Firstly I want to thank you for implementing such great project! It really simplifies the way the NuGet packages can be created. 

There are situations when we need to put .NET Framework 4.7.2 dll built from project reference inside lib\net5.0\SpecificFolder (or any other place under lib folder).
If it would be a .nuspec file I would want to generate such structure of files there:

<files>
	<file src="ClassLibraryNET5.dll" target="lib\net5.0"/>
	<file src="ClassLibraryNET472.dll" target="lib\net5.0\SpecificFolder"/>
  </files>

Could you explain how to do it?

## Steps to Reproduce

1. Open NugetizerProjectReferenceTest.sln from attached file.
[NugetizerProjectReferenceTest.zip](https://github.com/devlooped/nugetizer/files/6723291/NugetizerProjectReferenceTest.zip)
2. Pack NugetizerPack.msbuildproj project with Pack menu item from Visual Studio context menu.
3. Unzip the result NugetizerPack.1.0.0.nupkg file.
4. Observe - there is no ClassLibraryNET472.dll file under "lib\net5.0\SpecificFolder" folder.

## Expected Behavior

The project reference dll can be placed anywhere under lib folder of result NuGet package.

## Version Info

NuGetizer 0.7.1

**Comment by kzu** [comment]
Thanks a lot for the clean repro and your kind words :).

The way to pass additional properties to a project reference is via the `AdditionalProperties` metadata, like:

```xml
    <ProjectReference Include="..\ClassLibraryNET472\ClassLibraryNET472.csproj" 
                      AdditionalProperties="PackFolder=lib\net5.0\SpecificFolder" />
```

![image](https://user-images.githubusercontent.com/169707/123635652-4aaf6c00-d7f2-11eb-9ac3-d1e907f0c1d4.png)

**Comment by denjmpr** [comment]
It's great!
Thank you so much for help.
Additional question - is it some kind of standard or it might be simplified in future for such kind of packing?

**Comment by kzu** [comment]
An improvement for this has shipped! https://www.nuget.org/packages/nugetizer. Check the release notes https://github.com/devlooped/nugetizer/releases/tag/v0.7.2. You can now do:

```xml
    <ProjectReference Include="..\ClassLibraryNET472\ClassLibraryNET472.csproj" 
                      PackFolder="lib\net5.0\SpecificFolder" />
```

**Comment by denjmpr** [comment]
It's awesome!
Thank you so much!
