### ISSUE TITLE
Exclude assembly that is added by consumed package targets

### ISSUE THREAD

**Issue by quasarea** [devlooped/nugetizer#122]
### Discussed in https://github.com/devlooped/nugetizer/discussions/120

<div type='discussions-op-text'>

<sup>Originally posted by **quasarea** June 29, 2021</sup>
Hi, 

I have library that depends on Grpc.Core package. This package has a targets file that adds assemblies to output 
```
...
  <ItemGroup Condition="'$(Grpc_SkipNativeLibsCopy)' != 'true'">
    <Content Include="$(MSBuildThisFileDirectory)..\..\runtimes\win-x86\native\grpc_csharp_ext.x86.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>grpc_csharp_ext.x86.dll</Link>
      <Visible>false</Visible>
    </Content>
...
```

How can I exclude grpc_csharp_ext.x86.dll from being packaged? I have tried several combinations of 
```
    <PackInference Update="Content" PackExclude="**/grpc_csharp_ext.x86.dll;**/grpc_csharp_ext.x64.dll" />
    <PackInference Update="Content" PackExclude="$(OutputPath)/**/grpc_csharp_ext.x64.dll" />
    <PackInference Update="Content" PackExclude="$(OutputPath)/grpc_csharp_ext.x64.dll" />
    <PackInference Update="Content" PackExclude="**/grpc_csharp_ext.x64.dll" />
```
But nothing worked :(</div>

**Comment by SamMackrill** [comment]
I need to be able to do this too, seems like it is supported but can't get it to work.

**Comment by kzu** [comment]
Already answered in the discussion. https://github.com/devlooped/nugetizer/discussions/120
