### ISSUE TITLE
Packaging project generates package improperly

### ISSUE THREAD

**Issue by dansiegel** [devlooped/nugetizer#139]
## Describe the Bug

When using a packaging project to pack both my MSBuild tasks/targets with the actual library references a netcore50 target is added to the lib outputs with a number of runtime references.

Additionally the net472 target framework from the MSBuild project is added while a 3rd MSBuild project is only added as a NuGet dependency for the net472 target.

## Steps to Reproduce

See demo project...

- Have a multi-targeting library project
- Have a MSBuild targets project
- Have another MSBuild targets project that generates it's own core nuget.
- Have a msbuildproj packing project that packs each of these

## Expected Behavior

The target frameworks should come from the multi-targeting library. The net472 target from the MSBuild project should be ignored... the netcore50 target should not exist. The "Core" project should be added as an all around reference.

## Exception with Stack Trace

n/a

## Version Info

0.7.1

## Additional Info

[PackingDemo.zip](https://github.com/devlooped/nugetizer/files/6917905/PackingDemo.zip)

**Comment by kzu** [comment]
Took quite a bit of spelunking, but I found the issue, and a fix is on its way (to auto-merge as soon as tests pass).

Thanks for reporting it and for your patience as I found the time to look it up!
