### ISSUE TITLE
Files with absolute paths that do not specify a PackFolder are not included in the final nupkg

### ISSUE THREAD

**Issue by breidikl** [devlooped/nugetizer#162]
## Describe the Bug

Specifying a PackageFile to an absolute path without specifying a PackFolder causes that file not to be included in the resulting nupkg

## Steps to Reproduce

Specify a PackageFile with an absolute path as follows:

  `<PackageFile Include="$(BinaryLocation)\web\service\bin\Microsoft.Oasys.ServiceLogging.dll"/>`

BinaryLocation is an MSBuild property that resolves to an absolute path ("D:\OM\Import\x64\debug\pkgnuget_oasys\x-none\x64\oasys\x-none" in this case).

The diag logging for "AssignPackagePath" shows the following Task Parameter:

>       Files=
>           D:\OM\Import\x64\debug\pkgnuget_oasys\x-none\x64\oasys\x-none\web\service\bin\Microsoft.Oasys.ServiceLogging.dll
>                   OriginalItemSpec=
>                   PackageId=EngTelemetryLogging
>                   PackageReference=
>                   PackageReferencePath=
>                   PackageReferencePathProperty=
>                   PackFolder=None
>                   Platform=AnyCPU
>                   Source=Explicit

Which results in the following Output Item:

>       _PackageContent=
>           D:\OM\Import\x64\debug\pkgnuget_oasys\x-none\x64\oasys\x-none\web\service\bin\Microsoft.Oasys.ServiceLogging.dll
>                   OriginalItemSpec=D:\OM\Import\x64\debug\pkgnuget_oasys\x-none\x64\oasys\x-none\web\service\bin\Microsoft.Oasys.ServiceLogging.dll
>                   PackageFolder=
>                   PackageId=EngTelemetryLogging
>                   PackagePath=D:/OM/Import/x64/debug/pkgnuget_oasys/x-none/x64/oasys/x-none/web/service/bin/Microsoft.Oasys.ServiceLogging.dll
>                   PackageReference=
>                   PackageReferencePath=
>                   PackageReferencePathProperty=
>                   PackFolder=None
>                   Platform=AnyCPU
>                   Source=Explicit
>                   TargetPath=D:/OM/Import/x64/debug/pkgnuget_oasys/x-none/x64/oasys/x-none/web/service/bin/Microsoft.Oasys.ServiceLogging.dll

The resulting nupkg then does not include that file in the package.

## Expected Behavior

The expectation is that the file would be packed to the root of the package, which would likely mean stripping the absolute path to define the following:

>       _PackageContent=
>           D:\OM\Import\x64\debug\pkgnuget_oasys\x-none\x64\oasys\x-none\web\service\bin\Microsoft.Oasys.ServiceLogging.dll
>                   OriginalItemSpec=D:\OM\Import\x64\debug\pkgnuget_oasys\x-none\x64\oasys\x-none\web\service\bin\Microsoft.Oasys.ServiceLogging.dll
>                   PackageFolder=
>                   PackageId=EngTelemetryLogging
>                   PackagePath=Microsoft.Oasys.ServiceLogging.dll
>                   PackageReference=
>                   PackageReferencePath=
>                   PackageReferencePathProperty=
>                   PackFolder=None
>                   Platform=AnyCPU
>                   Source=Explicit
>                   TargetPath=Microsoft.Oasys.ServiceLogging.dll

## Version Info

NuGetizer 0.7.5

**Comment by kzu** [comment]
It wouldn't be intuitive to resort to packing on the root of the package. In most cases, you'll want to place the file somewhere else, and it's not clear which relative path should be used for that. For that reason, we don't do any special processing in that case, and in my testing, it actually results in an error (albeit a bit of an unintuitive one).

You can specify either a `PackFolder` or a `PackagePath` metadata for the `PackageFile` and decide precisely where you want it to land. For example:

```xml
<PackageFile Include="$(BinaryLocation)\web\service\bin\Microsoft.Oasys.ServiceLogging.dll" PackFolder="lib" />
```

Or, to place on the package root:

```xml
<PackageFile Include="$(BinaryLocation)\web\service\bin\Microsoft.Oasys.ServiceLogging.dll" PackagePath="Microsoft.Oasys.ServiceLogging.dll" />
```

Or generically, to include all files under that binary location (say):


```xml
<PackageFile Include="$(BinaryLocation)\**\*.dll" PackagePath="lib\$(TargetFramework)\%(Filename)%(Extension)" />
```
