### ISSUE TITLE
Yellow triangle on Nugetizer nuget package reference  under project  dependencies -> packages 

### ISSUE THREAD

**Issue by menaheme** [devlooped/nugetizer#196]
## Describe the Bug

theres a yellow triangle on Nugetizer nuget package reference  under project  dependencies -> packages.

## Steps to Reproduce

open VS 2022, create a console application using net 6.0 
install the Nugetizer 0.8 using the VS package manager GUI
you will see a triangle on Nugetizer nuget package reference  under project  dependencies -> packages.

## Expected Behavior

you should not have a triangle on Nugetizer nuget package reference  under project  dependencies -> packages.

## Version Info

Nugetizer 0.8 ,using MS logging , DI, MS Test SDK, Moq MS SqlClient.

**Comment by kzu** [comment]
Non-repro. VS will display a triangle very briefly while restore happens, but that's just how VS works.

![nugetized](https://user-images.githubusercontent.com/169707/179099727-3121e7f9-86d4-4b31-bf6a-a540dbfb260f.gif)
