### ISSUE TITLE
Support transitive package dependency of referenced (non-packing) project

### ISSUE THREAD

**Issue by khamza85** [devlooped/nugetizer#199]
## Describe the Bug

Sorry if a similar question was submitted before. Couldn't find anything similar.

Packaging project _Pkg_ with net472 TFM has a dependency on a project _NetStandardLib_ with netstandard2.0 TFM. _NetStandardLib_ has a package reference on say _Serialize.Linq_ package. I'd like to use _Pkg_ package from another net472 project and transitively depend on _Serialize.Linq_

## Steps to Reproduce
[NetStandardLib.zip](https://github.com/devlooped/nugetizer/files/9076567/NetStandardLib.zip)

Run _nugetize_ on _Pkg_. In the generated nuspec, I see
```
    <dependencies>
      <group targetFramework=".NETStandard2.0">
        <dependency id="Serialize.Linq" version="2.0.0" />
      </group>
      <group targetFramework=".NETFramework4.7.2" />
    </dependencies>
```
which makes _Serialize.Linq_ package impossible to be transitive dependency if you refer _Pkg_ package from another net472 project.

## Expected Behavior
Not even sure. Maybe nuspec should be generated something like this:

```
    <dependencies>
      <group targetFramework=".NETStandard2.0">
        <dependency id="Serialize.Linq" version="2.0.0" />
      </group>
      <group targetFramework=".NETFramework4.7.2">
         <dependency id="Serialize.Linq" version="2.0.0" />
       </group>
    </dependencies>
```

## Version Info

NuGetizer: v0.8.0

## Additional Info

I'm okay with any proper alternative solution. The only walkaround I found is to change _NetStandardLib_ TFM to net472 or multi-target it with net472 and netstandard2.0.

**Comment by kzu** [comment]
Thanks for reporting this issue @khamza85! It was indeed a foresight on my part, and is now working properly across multiple transitive reference levels and multi-targeting 💪
