### ISSUE TITLE
The target "GetPackageContents" does not exist in the project.

### ISSUE THREAD

**Issue by CoenraadS** [devlooped/nugetizer#226]
## Describe the Bug

I made a simple sdk style project to test packing with, nugetize gives the following error:

```
The target "GetPackageContents" does not exist in the project.
```

## Steps to Reproduce

`ClassLibrary1.csproj`
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>

</Project>
```

Just run `nugetize`

## Expected Behavior

Should of made a .nupkg

## Exception with Stack Trace

```text
error MSB4057: The target "GetPackageContents" does not exist in the project.
```

## Version Info

dotnet-nugetize version 0.8.0+cf829f761

**Comment by kzu** [comment]
`dotnet-nugetize` depends on the targets provided by `NuGetizer` itself. If you don't have that package installed, then things won't work.

This is by design. The tools is for consumers of NuGetizer.

Thanks!
