### ISSUE TITLE
Error message "valid version string" after adding nugetizer package

### ISSUE THREAD

**Issue by davidhunter22** [devlooped/nugetizer#271]
Hi, I added Nugetizer to an existing solution that builds fine.
I immediately started getting a build error before even trying to use Nugetizer
```
C:\Users\blah\.nuget\packages\nugetizer\0.9.1\build\NuGetizer.Shared.targets(279,5): error : '' is not a valid version string.
```
It's not clear to me what version string it's even talking about or why it is empty.
I am happy to start chopping my solution down to try to get to a root cause but was hoping that someone would have seen this before and know why it is happening. A search didn't turn up prior users complaining about this.

**Comment by davidhunter22** [comment]
After some investigation I discovered this only happens when using the Preview version of Visual Studio, so 17.5 Preview 3 currently. Does nugetizer try to find out what version of VS is in use and does not support 17.5 yet?

**Comment by kzu** [comment]
Hm, nope, it doesn't. Can you provide a repro project? Agreed that the error message isn't helpful. 

It's referring to the package version, which always had a default value of 1.9.0 in all current and previous stable versions of the .NET SDK ..

**Comment by kzu** [comment]
I'm nugetizing on 17.5 Preview 4 with no issues on multiple projects.

Could you attach a binlog or a repro please?

**Comment by kzu** [comment]
Closing due to insufficient info.
