### ISSUE TITLE
SponsorLink incorrectly configured

### ISSUE THREAD

**Issue by fde-lmag** [devlooped/nugetizer#340]
## Describe the Bug

With Version > 0.9.1 I am running into an error "SponsorLink incorrectly configured".
I do not understand what that means and what I have to do.
It would be great if the Sopnsor Link "Feature" could be explained in the Documentation.

## Steps to Reproduce

1. Create a Project In Visual Studio (used Version 2022)
2. Install Nugetizer Package with Version 0.9.4
3. Observe Error "SponsorLink incorrectly configured" in the Error Log

## Expected Behavior

Documentation (https://github.com/devlooped/nugetizer or https://www.clarius.org/nugetizer/) contains a Description of "SponsorLink", what it is, how it needs to be set up.

Even better would be if the Error Message itself contained some information or a link

**Comment by kzu** [comment]
Tried with a brand new project:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NuGetizer" Version="0.9.5" PrivateAssets="all" />
  </ItemGroup>

</Project>
```

Tried with 0.9.4 too. I cannot repro.

Can you include a repro please?

SponsorLink does not require any set up. I can be broken by people using custom targets that mess up SponsorLink checks (intentionally or otherwise), and thus, require a repro to diagnose. You can read more about SponsorLink at https://www.cazzulino.com/sponsorlink.html. 

Agreed that some docs on SponsorLink would be a good addition to the docs.

**Comment by fde-lmag** [comment]
Initially I was 
1. adding a new Project to a Solution
2. referencing the new Project from another Project that already had Nugetizer 0.9.1 installed
3. installing Nugetizer 0.9.5 on the new Project

... got the error and then tried a single project in a new solution and got the same error

Today, no matter what, i dont see the error anymore...

My bad, everything seems fine, seems to have been a fluke on my end

**Comment by kzu** [comment]
Yeah, I'm thinking that VS might have tried running the analyzer before the dependency was fully restored and loaded. But the project to protect reference might be a good indicator, will try that scenario a bit more.

Thanks for reporting and checking back!
