### ISSUE TITLE
Cleanup happens of every build

### ISSUE THREAD

**Issue by Aleksanderis** [devlooped/nugetizer#369]
## Describe the Bug

Seems like packages cleanup happens on every build, even if `GeneratePackageOnBuild=false` (also tried `PackOnBuild=false`).
Not sure if it's a desired behavior, but I would say it should be cleaning up only during packing. If it's a desired behaviour, then it would be good to have an option to control it like you want.

I can confirm that during such builds packages are not produced. It's just a build and cleanup what happens.

Cleaning up NuGet caches on every build makes my IDE (Rider) scream every time about missing references if consumer project is opened (sometimes only IDE restart helps to fix it).

## Version Info

Currently latest version - 1.0.1

**Comment by Aleksanderis** [comment]
Found a good enough workaround for now:
- Have `EnablePackCleanup=false` in `Directory.Build.props`
- Execute `dotnet pack` with additional properties - `/p:EnablePackCleanup=true`

**Comment by kzu** [comment]
Good catch @Aleksanderis! Will ship a fix today :)
