### ISSUE TITLE
'NuGetizer.SponsorLinker' exception happening randomly

### ISSUE THREAD

**Issue by Aleksanderis** [devlooped/nugetizer#370]
## Describe the Bug

With latest version (1.0.1) there is an exception happening during `dotnet pack`:

> CSC : error AD0001: Analyzer 'NuGetizer.SponsorLinker' threw an exception of type 'System.ArgumentNullException' with message 'Value cannot be null. (Parameter 'path2')'. [C:\Projects\ProjectX\ProjectX.csproj]

It happens not always, but quite often. I have 5 packable projects in the solution and some of them are randomly not packaged. I need to repeat `dotnet pack` several times until everything passed correctly.

## Version Info

Currently latest version - 1.0.1

**Comment by Aleksanderis** [comment]
I'm using Rider, but it happens outside IDE. I'm just running `dotnet pack` on solution level. It then packs all projects in solution which are packable (`<IsPackable>true</IsPackable>`).

**Comment by kzu** [comment]
Gotcha. Outside an IDE, nothing should be running. Will double check!

**Comment by kzu** [comment]
v1.0.2 shoud have the fix. Thanks for reporting!
