### ISSUE TITLE
Empty TargetFramework breaks the build

### ISSUE THREAD

**Issue by hankovich** [devlooped/nugetizer#416]
I have the following content in my csproj

```csproj
<PropertyGroup>
  <TargetFramework /> <!-- used to override the default value specified in Directory.Build.props -->
  <TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
</PropertyGroup>
```

And the build is broken 

```
10>------ Build started: Project: Extensions, Configuration: Debug Any CPU ------
10>C:\.nuget\packages\nugetizer\1.0.5\buildMultiTargeting\NuGetizer.targets(14,3): error MSB4020: The value "" of the "Project" attribute in element <Import> is invalid.
10>Done building project "Extensions.csproj" -- FAILED.
```

If I'll remove `<TargetFramework />` then everything will work as expected. As being said, it's needed to override the default value that comes from `Directory.Build.props`.

BTW calling `nugetize` from the command line shows another error `NuGetizer.targets(14,3): error MSB4020: ╨╖╨╜╨░╤З╨╡╨╜╨╕╨╡ "" ╨░╤В╤А╨╕╨▒╤Г╤В╨░ "Project" ╨▓ ╤Н╨╗╨╡╨╝╨╡╨╜╤В╨╡ <Import> ╨╜╨╡╨┤╨╛╨┐╤Г╤Б╤В╨╕╨╝╨╛.`, so it looks like errors in russian are not displayed correctly.

**Comment by kzu** [comment]
Closing for now since I couldn't repro. Please reopen if you can provide a reliable (and ideally isolated) repro.

Thanks!
