### ISSUE TITLE
Cannot imitate DevelopementDependency with PackageReference

### ISSUE THREAD

**Issue by FuzesiAkos** [devlooped/nugetizer#448]
## Describe the Bug

Hi!

I'm working on an application which needs to install and use nupkg-s runtime, and also we are developing a VSIX which has a project template for our customers to be able to create these nupkg-s. We have strict regulations for our software's nupkg install.

We recently switched from packages.config to PackageReference, and from NuGet.exe command line to NuGetizer 1.1.1. in the VSIX.

I need to imitate the DevelopementDependency attribute from packages.config and I can with NuGet.exe but I cannot with NuGetizer.
This is my setup in the csproj:

![csproj](https://github.com/devlooped/nugetizer/assets/32295406/8e43c28b-94ed-4f24-aa38-8cd22fafe344)

The outcome with NuGet.exe (which we except):
![NuGetExeLib](https://github.com/devlooped/nugetizer/assets/32295406/6ce379ac-2925-4942-9f53-a4983ce61b42)
![NuGetExeNuspec](https://github.com/devlooped/nugetizer/assets/32295406/0aa5df01-8b19-44a8-a78b-866a9dc45d18)

The outcome with NuGetizer.1.1.1
![NuGetizerLib](https://github.com/devlooped/nugetizer/assets/32295406/0666e633-ee77-4afa-80c6-f28643b14483)
![NuGetizerNuspec](https://github.com/devlooped/nugetizer/assets/32295406/837e2fe6-85c3-49a6-8a97-4235614d291d)

## Expected Behavior
We except the behavior what NuGet.exe already does:
1. We don't want to include the dll's into the lib folder as we already load them in our own software, also we have strict dll loading regulations and we cannot load these from outside.
2. We don't want these nupkg-s to appear as dependencies in the nupkg.

## Version Info
NuGetizer.1.1.1 and NuGet.commandline 6.7.0

## Additional Info
We found a workaround: Simply remove the dlls from the nupkg with an afterpack build script, which is very odd and we would be very happy with the right solution.
Also we tried a bunch of <PrivateAsset> and <ExcludeAsset> combinations, none of them worked, neither the one at the bottom of the following page, which is a [NuGet recommendation](https://github.com/NuGet/Home/wiki/DevelopmentDependency-support-for-PackageReference#example)

**Comment by FuzesiAkos** [comment]
Worth to mention: Not all PrivateAssets are packed into  the lib folder, but two very important to not be there. These two are heavily used in the VSIX project and are dll-s from our main software which will use the packages runtime.

The full PackageReferences including the ones from the bug report:
![image](https://github.com/devlooped/nugetizer/assets/32295406/48a81ffa-9243-4f04-879e-8d7f365484a2)

**Comment by kzu** [comment]
Don't set the package reference as `PrivateAssets=all` since that makes them effectively "pack with my primary output", which is the most sensible default in that case.  You can also use the ubiquitous `Pack=false` metadata attribute on the package reference.
